name: Build Workload

on:
  push:
    branches: [ main ]
    paths:
    - 'workload/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'workload/**'
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Pre-release tag name'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      env:
        PULLREQUEST_ID: ${{ github.event.number }}
        PRERELEASE_TAG: ${{ github.event.inputs.prerelease }}
      run: make
      working-directory: ./workload

    - uses: actions/upload-artifact@v2
      with:
        name: tizen-workload-pkgs
        path: ./workload/bin/nuget-unsigned/*.nupkg

