name: Release Workload

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Pre-release tag name'
        required: true
      isStableRelease:
        description: 'Stable release?'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Wix toolset
      run: sudo apt-get install -y wixl

    - name: Build
      env:
        PRERELEASE_TAG: ${{ github.event.inputs.prerelease }}
        IS_STABLE_RELEASE_TAG: ${{ fromJson(github.event.inputs.isStableRelease) }}
      run: make msi -d
      working-directory: ./workload

    - name: Push packages to NuGet.org
      run: |
        dotnet nuget push ./workload/out/nuget-unsigned/Samsung.*.nupkg \
                      -k ${{ secrets.NUGET_APIKEY }} \
                      -s https://api.nuget.org/v3/index.json \
                      -t 3000

    - name: Upload msi package to S3
      uses: TizenAPI/tizenfx-build-actions/s3-upload@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        region: ap-northeast-2
        bucket: workload-bin
        file: ./workload/out/windows/Samsung.NET.Workload.Tizen.*.msi
        folder: windows
